build:
  dependencies:
    before:
      - pip install virtualenv
      - pip install colorlog pyyaml psutil lxml cssselect nose urwid coverage six pylint selenium progressbar33 locustio pyvirtualdisplay
    override:
      - true
  tests:
    override:
      -
        command: ./run-test.sh
        coverage:
          file: .coverage
          #config: .coveragerc
          format: py-cc