sudo: false
language: python
dist: xenial
cache: pip  # use caching for pip's packages to speed up builds

branches:
  only:
  - master

os: linux

python:
#- "3.5"
#- "3.6"
- "3.8"

env:
  global:
  - DISPLAY=:99.0
  - PIP_INSTALL="pip install"
  - GENERAL_EXCLUDE="--exclude-dir=tests/resources --exclude-dir=tests/ci"
  - PYTHON=python

matrix:
  include:
#  - os: osx
#    name: "Python3.7 on macOS"
#    osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
#    language: shell
#    env:
#    - PYTHON=python3
#    - PIP_INSTALL="sudo pip3 install"
#    - RVM_KEY="409B6B1796C275462A1703113804BB82D39DC0E3"
#    - OSX_EXCLUDE="--exclude-test=tests.modules.selenium.test_csharp"
#    before_install:
#    - gpg --keyserver hkp://keys.gnupg.net --recv-keys $RVM_KEY && rvm get stable || echo "rvm update fail"
#    before_script:
#      - sudo nohup bash -c "xvfb :99 &"
#      - $PYTHON tests/resources/httpserver/start.py &
#    script:
#      - coverage run --source=. -m nose tests -v $GENERAL_EXCLUDE $OSX_EXCLUDE --with-timer --timer-top-n 30

  - os: windows
    name: "Python3.8 on Windows"
    language: sh
    env:
      - PYTHON="C:/Python38/python.exe"
      - PIP_INSTALL="C:/Python38/python.exe -m pip install"
      - PATH=c/Python38:/c/Python38/Scripts:$PATH
      - R_PATH=C:/Ruby22/bin
      - PYTHON_VERSION="3.8.x"
      - PYTHON_ARCH="64"
#      - NODEJS_VERSION="10"
    before_install:
    - choco install python --version 3.8.1
    - $PYTHON --version
    - $PYTHON -m ensurepip
    - $PYTHON -m pip install --upgrade pip
    install:
    - $PIP_INSTALL pip wheel --upgrade
    - $PIP_INSTALL pyyaml==3.12
    - $PIP_INSTALL -r requirements.txt
    - $PIP_INSTALL -r tests/ci/requirements.txt
    - choco install nodejs.install
    before_script:
    - ruby -v
    - gem -v
    - rspec --version
    - node --version
    - locust --version
#    - $PYTHON tests/resources/httpserver/start.py ;
    script:
    - dir tests
    - $PYTHON -m nose tests --exclude-dir=tests/resources --exclude-dir=tests/ci

addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
    - openjdk-8-jdk
    - mono-complete
    - python3-tk

before_install:
- mono --version

install:
- gem install rspec
- $PIP_INSTALL "pyyaml<5.1"
- $PIP_INSTALL -r requirements.txt
- $PIP_INSTALL -r tests/ci/requirements.txt

#before_script:
#- nohup bash -c "Xvfb :99 &"
#- $PYTHON tests/resources/httpserver/start.py &

script:
- coverage run --source=. -m nose tests -v $GENERAL_EXCLUDE --with-timer --timer-top-n 30

after_success:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then coverage report -m && codecov; fi
