sudo: false
language: python
group: travis_latest
cache: pip  # use caching for pip's packages to speed up builds

branches:
  only:
  - master

env:
  global:
  - DISPLAY=:99.0
  - PIP_INSTALL="pip install"
  - GENERAL_EXCLUDE="--exclude-dir=tests/resources --exclude-dir=tests/ci"
  - PYTHON=python

matrix:
  include:
  - os: linux
    name: "Python3.5 on Linux"
    python: 3.5
    before_install:
      - mono --version
    install:
      - gem install rspec
      - $PIP_INSTALL "pyyaml<5.1"
      - $PIP_INSTALL -r requirements.txt
      - $PIP_INSTALL -r tests/ci/requirements.txt
    before_script:
      - nohup bash -c "Xvfb :99 &"
      - $PYTHON tests/resources/httpserver/start.py &
    script:
      - coverage run --source=. -m nose tests -v $GENERAL_EXCLUDE --with-timer --timer-top-n 30

  - os: linux
    name: "Python3.6 on Linux"
    python: 3.6
    before_install:
      - mono --version
    install:
      - gem install rspec
      - $PIP_INSTALL "pyyaml<5.1"
      - $PIP_INSTALL -r requirements.txt
      - $PIP_INSTALL -r tests/ci/requirements.txt
    before_script:
      - nohup bash -c "Xvfb :99 &"
      - $PYTHON tests/resources/httpserver/start.py &
    script:
      - coverage run --source=. -m nose tests -v $GENERAL_EXCLUDE --with-timer --timer-top-n 30

  - os: linux
    name: "Python3.7 on Linux"
    python: 3.7
    before_install:
    - mono --version
    install:
    - gem install rspec
    - $PIP_INSTALL "pyyaml<5.1"
    - $PIP_INSTALL -r requirements.txt
    - $PIP_INSTALL -r tests/ci/requirements.txt
    before_script:
    - nohup bash -c "Xvfb :99 &"
    - $PYTHON tests/resources/httpserver/start.py &
    script:
    - coverage run --source=. -m nose tests -v $GENERAL_EXCLUDE --with-timer --timer-top-n 30
    after_success:
    - coverage report -m && codecov

  - os: osx
    name: "Python3.7 on macOS"
    osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
    language: shell
    env:
    - PYTHON=python3
    - PIP_INSTALL="sudo pip3 install"
    - RVM_KEY="409B6B1796C275462A1703113804BB82D39DC0E3"
    - OSX_EXCLUDE="--exclude-test=tests.modules.selenium.test_csharp"
    before_install:
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys $RVM_KEY && rvm get stable || echo "rvm update fail"
    install:
    - gem install rspec
    - $PIP_INSTALL "pyyaml<5.1"
    - $PIP_INSTALL -r requirements.txt
    - $PIP_INSTALL -r tests/ci/requirements.txt
    before_script:
      - sudo nohup bash -c "xvfb :99 &"
      - $PYTHON tests/resources/httpserver/start.py &
    script:
      - coverage run --source=. -m nose tests -v $GENERAL_EXCLUDE $OSX_EXCLUDE --with-timer --timer-top-n 30

  - os: windows
    name: "Python3.7 on Windows"
    language: shell
    before_install:
    - choco install python --version 3.7.4
    - python -m ensurepip
    - python -m pip install --upgrade pip
    env:
    - PYTHON=C:\\Python37
    - PATH=c/Python37:/c/Python37/Scripts:$PATH
    - R_PATH=C:\Ruby22\bin;
    install:
    - $PYTHON/python.exe -m pip install pip wheel --upgrade
    - $PYTHON/python.exe -m pip install pyyaml==3.12
    - $PYTHON/python.exe -m pip install -r requirements.txt
    - $PYTHON/python.exe -m pip install -r tests/ci/requirements.txt
#    - set R_PATH=C:\Ruby22\bin;%PATH%\Scripts\;%R_PATH%
    - gem install rspec
    before_test:
    - ruby -v
    - gem -v
    - rspec --version
    - node --version
    - locust --version
    - python tests/resources/httpserver/start.py
    script:
    - python -m nose tests -v --exclude-dir=tests/resources --exclude-dir=tests/ci --with-coverage --cover-inclusive

addons:
  firefox: latest
  apt:
    packages:
    - openjdk-8-jdk
    - mono-complete
    - python-tk
    - python3-tk
