sudo: false
language: python

matrix:
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.3
  - os: linux
    python: 3.4
  - os: linux
    python: 3.5
#  - os: osx
#    language: generic

addons:
  firefox: "54.0"
  apt:
    packages:
      - oracle-java8-set-default

install:
- nvm install 4.2
- nvm use 4.2
- gem install rspec
- pip install colorlog jsonpath-rw pyyaml psutil lxml cssselect urwid six selenium progressbar33 locustio pyvirtualdisplay astunparse ipaddress
- pip install git+https://github.com/Blazemeter/apiritif.git@master
- pip install --upgrade codecov nose nose-exclude
script: coverage run  --source=. `which nosetests` tests --exclude-dir=tests/resources
after_success:
- coverage report -m
- codecov
