language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: "pip install colorlog pyyaml psutil lxml cssselect grip urwid six selenium progressbar33 locustio"
script: nosetests
