environment:
  matrix:
    - PYTHON: "C:\\Python27"
    #- PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    #- PYTHON: "C:\\Python35"

install:
  - "%PYTHON%\\python.exe -m pip install nose"
  - "%PYTHON%\\python.exe -m pip install colorlog pyyaml psutil lxml==3.4.2 cssselect urwid six selenium progressbar33 locustio pyvirtualdisplay"

build: off

test_script:
  - "%PYTHON%\\python.exe -m nose"

after_test:
  - "%PYTHON%\\python.exe setup.py clean sdist"

artifacts:
  - path: dist\*
